apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-rest
  template:
    metadata:
      labels:
        app: notification-rest
    spec:
      containers:
      - name: notification-rest
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/notification:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-gunicorn-server", "--workers", "8"]
        ports:
        - name: rest
          containerPort: 5000
        envFrom:
          - secretRef:
              name: notification-secret
          - configMapRef:
              name: notification-conf
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
      - name: notification-kafka
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/notification:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-kafka-consumer"]
        envFrom:
          - secretRef:
              name: notification-secret
          - configMapRef:
              name: notification-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
